### PR TITLE
chore: replace rubinius 3 with rubinius 5

### PR DESCRIPTION
**Pull request by salzig**
Instead of just removing the rubinius test run, replace it with a newer version. let's see if this runs successfully.

### CODE REVIEW

**Comment by stefan-eventinc** [comment]
@salzig should that be moved into the AKRA namespace?

**Comment by salzig** [comment]
@emrox, already is, as a fork of this one. Which means creating pull-request defaults to be based upon yours, and i missed to change that for this PR. Sorry for the notification.

**Comment by emrox** [comment]
@salzig no problem. I think I'll archive this one to reduce future confusion

**Comment by emrox** [comment]
@salzig and happy Hacktober ;-)

**Pull request closed without merging**
